name:                stepik-haskell
version:             0.1.0.0
github:              "waffleboot/stepik-haskell"
license:             BSD3
author:              "Andrei Yangabishev"
maintainer:          "waffleboot@gmail.com"
copyright:           "value"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            value

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/waffleboot/stepik-haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  stepik-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stepik-haskell
    - transformers
    - mtl
